import os
from datetime import datetime
from docx import Document
from docx.shared import Inches

# Paths
BASE_DIR = os.path.abspath(os.path.dirname(__file__))
REPORT_PATH = os.path.join(BASE_DIR, 'progress_report.docx')

# Create document
doc = Document()

def add_heading(text, level=1):
    doc.add_heading(text, level=level)

def add_paragraph(text):
    doc.add_paragraph(text)

def add_list(items):
    for item in items:
        doc.add_paragraph(item, style='List Bullet')

def add_image(path, width=Inches(4)):
    if os.path.exists(path):
        doc.add_picture(path, width=width)

def main():
    # Title page
    doc.add_heading('Face Recognition Attendance System – Progress Report', 0)
    doc.add_paragraph(f'Date: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}')
    doc.add_paragraph('Generated by Antigravity AI assistant')
    doc.add_page_break()

    # Overview
    add_heading('Overview')
    add_paragraph('This document summarizes the work performed so far on the attendance system, covering data generation, face detection, recognizer training, dataset encryption, and tooling configuration.')

    # Dataset Generation
    add_heading('Dataset Generation', level=2)
    add_paragraph('Synthetic facial images for three subjects (alice, bob, charlie) were generated with variations: frontal, angled, and low‑light conditions. Files are stored under `dataset/` with 10 images per subject (30 images total).')
    # Example images (first of each subject)
    for person in ['alice', 'bob', 'charlie']:
        img_path = os.path.join(BASE_DIR, 'dataset', person, f'img_1_frontal.jpg')
        add_paragraph(f'Example – {person.title()} (frontal)')
        add_image(img_path)

    # Face Detection
    add_heading('Face Detection', level=2)
    add_paragraph('Implemented `detect.py` using OpenCV Haar Cascade. The detector was evaluated on sample images, successfully locating faces in most conditions, with failures noted in low‑light scenarios.')
    add_image(os.path.join(BASE_DIR, 'output', 'frontal_face.png'))
    add_image(os.path.join(BASE_DIR, 'output', 'low_light_face.png'))

    # Recognizer Training
    add_heading('Recognizer Training', level=2)
    add_paragraph('Created `train_recognizer.py` which extracts 200×200 grayscale face patches, trains an OpenCV LBPH recognizer, and saves the model and label map. The model achieved high confidence on frontal images and moderate confidence on angled/low‑light images.')
    add_image(os.path.join(BASE_DIR, 'output_recognition', 'alice_frontal_predicted.png'))
    add_image(os.path.join(BASE_DIR, 'output_recognition', 'bob_lowlight_predicted.png'))

    # Dataset Encryption
    add_heading('Dataset Encryption', level=2)
    add_paragraph('Added `encrypt_dataset.py` providing three CLI commands:')
    add_list([
        '`encrypt` – encrypt all images using Fernet (AES‑128‑CBC + HMAC‑SHA256) and store under `encrypted_dataset/`.',
        '`decrypt` – restore plaintext images to `dataset_decrypted/`.',
        '`status` – report presence of plaintext, encrypted data, and the secret key.'
    ])
    add_paragraph('Encryption generated a `secret.key` file and a `manifest.json` describing the encrypted assets (30 files, ~9.5 MiB).')
    add_paragraph('Decryption was verified with a hash‑check; all 30 files matched the original data (0 mismatches).')

    # IDE Configuration
    add_heading('IDE Configuration', level=2)
    add_paragraph("Created `.vscode/settings.json` to point the workspace interpreter to the project's virtual environment (`.venv`). This resolves the previous import warning for `cryptography`.")

    # Final Remarks
    add_heading('Next Steps', level=2)
    add_paragraph('• Securely back up `secret.key` in a separate location.\n• Delete the plaintext `dataset/` folder if encrypt‑at‑rest is required.\n• Integrate decryption on‑the‑fly in the training pipeline if needed.\n• Continue improving detection robustness (e.g., using CNN‑based detectors).')

    # Project File Structure
    def add_file_tree(root_path, indent=""):
        for entry in sorted(os.listdir(root_path)):
            entry_path = os.path.join(root_path, entry)
            if os.path.isdir(entry_path):
                doc.add_paragraph(f"{indent}📁 {entry}/")
                add_file_tree(entry_path, indent + "    ")
            else:
                doc.add_paragraph(f"{indent}📄 {entry}")

    add_heading('Project File Structure', level=2)
    add_file_tree(BASE_DIR)

    # Save document
    doc.save(REPORT_PATH)
    print(f"[+] Progress report generated at: {REPORT_PATH}")

if __name__ == '__main__':
    main()
